name: algoritmos_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/asset/fonts

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: asset/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: asset/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: asset/fonts/Montserrat-Bold.ttf
          weight: 700
